name: Deploy to S3 and CloudFront

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1  # Twój region AWS

    - name: Fix flutter SDK folder permission
      run: git config --global --add safe.directory /tmp/flutter/--

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'latest'
    
    - name: Switch to beta channel
      run: flutter channel beta
    
    - name: Upgrade Flutter to beta
      run: flutter upgrade

    - name: Build project (optional, if needed)
      run: |
        flutter build web --release --wasm --dart-define=FLUTTER_WEB_CANVASKIT_URL=/canvaskit/ --no-web-resources-cdn --no-tree-shake-icons

    - name: Sync specific folder to S3
      run: |
        aws s3 sync build/web/ s3://zobmat-hosting --delete

    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id E3U8GJQ0UV4TUI --paths "/*"
